### ISSUE TITLE
Angular 5+

### ISSUE THREAD

**Issue by ryanbuening** [EliCDavis/ng-conditionally-validate#1]
You mention this is an Angular 4 library. Is this working with Angular 5? Is development still active?

**Comment by EliCDavis** [comment]
I just created an empty angular 5 project and installed the node module and it seems to work fine with it. 

It's not under development because I don't have anything in mind to add, it does the job I set out to do.

If you have any issues with your angular 5 projects or have a feature request, feel free to open up another issue!
